name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Build & Test
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Enable docker layer cache
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Pull docker images
        run: docker-compose pull
        continue-on-error: true
      - name: Lint the source
        run: docker compose run --rm builder yarn lint
      - name: Transpile into dist
        run: docker compose run --rm builder yarn build
      - name: Run tests
        run: docker compose run --rm runner yarn test
      - name: Stop containers
        if: always()
        run: docker compose down
